const eslintPrettier = require("eslint-plugin-prettier");
const eslintParser = require("@typescript-eslint/parser");
const eslintPlugin = require("@typescript-eslint/eslint-plugin");
const eslintImport = require("eslint-plugin-import");
const eslintJsdoc = require("eslint-plugin-jsdoc");

const defineConfig = require("eslint/config").defineConfig;

const rules = {
  "@typescript-eslint/adjacent-overload-signatures": "error",
  "@typescript-eslint/array-type": ["error", { default: "array" }],
  "@typescript-eslint/await-thenable": "error",
  "@typescript-eslint/ban-ts-comment": "error",
  "@typescript-eslint/consistent-indexed-object-style": [
    "error",
    "index-signature",
  ],
  "@typescript-eslint/consistent-return": "error",
  "@typescript-eslint/consistent-type-assertions": "error",
  "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
  "@typescript-eslint/consistent-type-exports": "error",
  "@typescript-eslint/default-param-last": "error",
  "@typescript-eslint/dot-notation": "error",
  "@typescript-eslint/explicit-function-return-type": "error",
  "@typescript-eslint/explicit-module-boundary-types": "error",
  "@typescript-eslint/member-ordering": [
    "error",
    { default: { optionalityOrder: "required-first", order: "as-written" } },
  ],
  "@typescript-eslint/naming-convention": [
    "error",
    {
      selector: "autoAccessor",
      format: ["camelCase"],
      leadingUnderscore: "forbid",
      trailingUnderscore: "forbid",
    },
    {
      selector: "classicAccessor",
      format: ["camelCase"],
      leadingUnderscore: "forbid",
      trailingUnderscore: "forbid",
    },
    {
      selector: "classProperty",
      format: ["camelCase", "snake_case", "UPPER_CASE"],
      leadingUnderscore: "forbid",
      trailingUnderscore: "forbid",
    },
    {
      selector: "enumMember",
      format: ["UPPER_CASE"],
      leadingUnderscore: "forbid",
      trailingUnderscore: "forbid",
    },
    {
      selector: "import",
      format: ["camelCase", "snake_case"],
      leadingUnderscore: "forbid",
      trailingUnderscore: "forbid",
    },
    {
      selector: "method",
      format: ["camelCase"],
      leadingUnderscore: "forbid",
      trailingUnderscore: "forbid",
    },
    {
      selector: "objectLiteralProperty",
      format: ["camelCase", "snake_case", "UPPER_CASE"],
      leadingUnderscore: "forbid",
      trailingUnderscore: "forbid",
    },
    {
      selector: "parameter",
      format: ["camelCase"],
      leadingUnderscore: "allow",
      trailingUnderscore: "forbid",
    },
    {
      selector: "parameterProperty",
      format: ["camelCase"],
      leadingUnderscore: "forbid",
      trailingUnderscore: "forbid",
    },
    {
      selector: "typeLike",
      format: ["PascalCase"],
      leadingUnderscore: "forbid",
      trailingUnderscore: "forbid",
    },
    {
      selector: "variable",
      format: ["camelCase", "PascalCase", "snake_case"],
      leadingUnderscore: "forbid",
      trailingUnderscore: "forbid",
    },
  ],
  "@typescript-eslint/no-array-constructor": "error",
  "@typescript-eslint/no-array-delete": "error",
  "@typescript-eslint/no-base-to-string": "error",
  "@typescript-eslint/no-confusing-non-null-assertion": "error",
  "@typescript-eslint/no-confusing-void-expression": "error",
  "@typescript-eslint/no-deprecated": "error",
  "@typescript-eslint/no-duplicate-type-constituents": "error",
  "@typescript-eslint/no-dynamic-delete": "error",
  "@typescript-eslint/no-empty-function": "error",
  "@typescript-eslint/no-empty-interface": "error",
  "@typescript-eslint/no-empty-object-type": "error",
  "@typescript-eslint/no-extra-non-null-assertion": "error",
  "@typescript-eslint/no-floating-promises": "error",
  "@typescript-eslint/no-invalid-this": "error",
  "@typescript-eslint/no-invalid-void-type": "error",
  "@typescript-eslint/no-meaningless-void-operator": "error",
  "@typescript-eslint/no-misused-promises": "error",
  "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
  "@typescript-eslint/no-redundant-type-constituents": "error",
  "@typescript-eslint/no-shadow": "error",
  "@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
  "@typescript-eslint/no-unnecessary-condition": "error",
  "@typescript-eslint/no-unnecessary-template-expression": "error",
  "@typescript-eslint/no-unnecessary-type-arguments": "error",
  "@typescript-eslint/no-unnecessary-type-assertion": "error",
  "@typescript-eslint/no-unnecessary-type-constraint": "error",
  "@typescript-eslint/no-unnecessary-type-conversion": "error",
  "@typescript-eslint/no-unsafe-enum-comparison": "error",
  "@typescript-eslint/no-unsafe-function-type": "error",
  "@typescript-eslint/no-unsafe-return": "error",
  "@typescript-eslint/no-unsafe-type-assertion": "error",
  "@typescript-eslint/no-unused-expressions": "error",
  "@typescript-eslint/no-unused-vars": [
    "error",
    {
      argsIgnorePattern: "^_",
      caughtErrorsIgnorePattern: "^_",
      varsIgnorePattern: "^_",
    },
  ],
  "@typescript-eslint/no-use-before-define": "error",
  "@typescript-eslint/no-useless-constructor": "error",
  "@typescript-eslint/no-wrapper-object-types": "error",
  "@typescript-eslint/non-nullable-type-assertion-style": "error",
  "@typescript-eslint/only-throw-error": "error",
  "@typescript-eslint/prefer-as-const": "error",
  "@typescript-eslint/prefer-promise-reject-errors": "error",
  "@typescript-eslint/prefer-readonly": "error",
  "@typescript-eslint/promise-function-async": "error",
  "@typescript-eslint/require-await": "error",
  "@typescript-eslint/return-await": ["error", "always"],
  "@typescript-eslint/strict-boolean-expressions": [
    "error",
    {
      allowAny: false,
      allowNullableBoolean: false,
      allowNullableEnum: false,
      allowNullableNumber: false,
      allowNullableObject: false,
      allowNullableString: false,
      allowNumber: false,
      allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing: false,
      allowString: false,
    },
  ],
  "@typescript-eslint/switch-exhaustiveness-check": "error",
  "@typescript-eslint/typedef": [
    "error",
    {
      arrayDestructuring: true,
      arrowParameter: true,
      memberVariableDeclaration: true,
      objectDestructuring: true,
      parameter: true,
      propertyDeclaration: true,
      variableDeclaration: true,
      variableDeclarationIgnoreFunction: false,
    },
  ],
  "@typescript-eslint/unbound-method": "error",
  "array-callback-return": "error",
  "arrow-parens": ["error", "always"],
  "block-scoped-var": "error",
  "consistent-return": "off",
  curly: ["error", "multi"],
  "default-case-last": "error",
  "default-param-last": "off",
  "dot-notation": "off",
  eqeqeq: ["error", "always"],
  "import/newline-after-import": "error",
  "import/no-cycle": "error",
  "import/no-duplicates": "error",
  "import/no-mutable-exports": "error",
  "import/order": ["error", { groups: ["builtin", "external", "internal"] }],
  "jsdoc/check-tag-names": "error",
  "jsdoc/require-description": "error",
  "jsdoc/require-param": "error",
  "jsdoc/require-returns": "error",
  "no-alert": "error",
  "no-array-constructor": "off",
  "no-bitwise": "error",
  "no-console": "error",
  "no-constant-binary-expression": "error",
  "no-constant-condition": ["error", { checkLoops: "all" }],
  "no-debugger": "error",
  "no-duplicate-case": "error",
  "no-duplicate-imports": "error",
  "no-empty-function": "off",
  "no-eval": "error",
  "no-fallthrough": "error",
  "no-floating-promises": "off",
  "no-global-assign": "error",
  "no-implicit-coercion": "error",
  "no-implicit-globals": "error",
  "no-invalid-this": "off",
  "no-lone-blocks": "error",
  "no-loop-func": "error",
  "no-loss-of-precision": "error",
  "no-mixed-operators": "error",
  "no-new-func": "error",
  "no-new-wrappers": "error",
  "no-param-reassign": "error",
  "no-process-exit": "error",
  "no-redeclare": "error",
  "no-return-assign": "error",
  "no-return-await": "error",
  "no-self-assign": "error",
  "no-self-compare": "error",
  "no-shadow": "off",
  "no-template-curly-in-string": "error",
  "no-throw-literal": "off",
  "no-unneeded-ternary": "error",
  "no-unreachable": "error",
  "no-unreachable-loop": "error",
  "no-unsafe-optional-chaining": "error",
  "no-unused-expressions": "off",
  "no-unused-vars": "off",
  "no-use-before-define": "off",
  "no-useless-catch": "error",
  "no-useless-constructor": "off",
  "no-useless-return": "error",
  "no-var": "error",
  "prefer-arrow-callback": "error",
  "prefer-const": "error",
  "prefer-object-spread": "error",
  "prefer-template": "error",
  "prettier/prettier": "error",
  "require-atomic-updates": "error",
};

module.exports = defineConfig([
  {
    ignores: ["dist/**", "node_modules/**"],
  },
  {
    files: ["**/*.js", "**/*.cjs", "**/*.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
    },
    plugins: {
      prettier: eslintPrettier,
      import: eslintImport,
      jsdoc: eslintJsdoc,
    },
    rules: {
      "array-callback-return": "error",
      "arrow-parens": ["error", "always"],
      "block-scoped-var": "error",
      "consistent-return": "error",
      curly: ["error", "multi"],
      "default-case-last": "error",
      "default-param-last": "error",
      "dot-notation": "error",
      eqeqeq: ["error", "always"],
      "import/newline-after-import": "error",
      "import/no-cycle": "error",
      "import/no-duplicates": "error",
      "import/no-mutable-exports": "error",
      "import/no-unresolved": "error",
      "import/order": [
        "error",
        { groups: ["builtin", "external", "internal"] },
      ],
      "jsdoc/check-tag-names": "error",
      "jsdoc/require-description": "error",
      "jsdoc/require-param": "error",
      "jsdoc/require-returns": "error",
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-bitwise": "error",
      "no-console": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": ["error", { checkLoops: "all" }],
      "no-debugger": "error",
      "no-duplicate-case": "error",
      "no-duplicate-imports": "error",
      "no-empty-function": "error",
      "no-eval": "error",
      "no-fallthrough": "error",
      "no-global-assign": "error",
      "no-implicit-coercion": "error",
      "no-implicit-globals": "error",
      "no-invalid-this": "error",
      "no-lone-blocks": "error",
      "no-loop-func": "error",
      "no-loss-of-precision": "error",
      "no-mixed-operators": "error",
      "no-new-func": "error",
      "no-new-wrappers": "error",
      "no-param-reassign": "error",
      "no-process-exit": "error",
      "no-redeclare": "error",
      "no-return-assign": "error",
      "no-return-await": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-shadow": "error",
      "no-template-curly-in-string": "error",
      "no-throw-literal": "error",
      "no-unneeded-ternary": "error",
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-expressions": "error",
      "no-unused-vars": "error",
      "no-use-before-define": "error",
      "no-useless-catch": "error",
      "no-useless-constructor": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "prefer-arrow-callback": "error",
      "prefer-const": "error",
      "prefer-object-spread": "error",
      "prefer-template": "error",
      "prettier/prettier": "error",
      "require-atomic-updates": "error",
    },
  },
  {
    files: ["src/**/*.ts", "src/**/*.tsx"],
    languageOptions: {
      parser: eslintParser,
      parserOptions: {
        project: ["./tsconfig.json"],
        ecmaVersion: "latest",
        sourceType: "module",
      },
    },
    plugins: {
      "@typescript-eslint": eslintPlugin,
      prettier: eslintPrettier,
      import: eslintImport,
      jsdoc: eslintJsdoc,
    },
    rules: rules,
  },
  {
    files: ["test/**/*.ts", "test/**/*.tsx"],
    languageOptions: {
      parser: eslintParser,
      parserOptions: {
        project: ["./test/tsconfig.json"],
        ecmaVersion: "latest",
        sourceType: "module",
      },
    },
    plugins: {
      "@typescript-eslint": eslintPlugin,
      prettier: eslintPrettier,
      import: eslintImport,
      jsdoc: eslintJsdoc,
    },
    rules: rules,
  },
]);
